#ifndef ERRORS_HPP
#define ERRORS_HPP

#define ROOM_NOT_FOUND "Error 101: The desired room was not found."
#define RESERVE_NOT_FOUND "Error 102: Your reservation was not found."
#define SUCCESSFULLY_ADDED "Error 104: Successfully added."
#define SUCCESSFULLY_MODIFIED "Error 105: Successfully modified."
#define SUCCESSFULLY_DELETED "Error 106: Successfully deleted."
#define LOW_BALANCE "Error 108: Your account balance is not enough."
#define ROOM_IS_FULL "Error 109: The room capacity is full."
#define ROOM_EXIST "Error 111: This room already exists."
#define USER_LOGGED_IN "Error 230: User logged in."
#define USER_SUCCESSFULLY_SIGN_UP "Error 231: User successfully signed up."
#define USER_SIGNED_UP "Error 311: User Signed up. Enter your password, purse, phone and address."
#define INFORMATION_CHANGED "Error 312: Information was changed successfully."
#define INVALID_VALUE "Error 401: Invalid value!"
#define ACCESS_DENIED "Error 403: Access Denied."
#define INVALID_CAPACITY "Error 412: Invalid capacity value!"
#define SUCCESSFULLY_LEAVING "Error 413: Successfully leaving."
#define INVALID_USERNAME_OR_PASSWORD "Error 430: Invalid username or password."
#define USER_EXISTED "Error 451: User already existed!"
#define BAD_SEQUENCE_OF_COMMANDS "Error 503: Bad sequence of commands."
#define LOGOUT_SUCCESSFULLY "Error 201: User logged out successfully."
#define SUCCESSFULLY_DONE "Error 110: Successfully done."
#endif